# Pandas
Destaques da Biblioteca

- Um objeto DataFrame rápido e eficiente para manipulação de dados com indexação integrada

- Ferramentas para leitura e gravação de dados entre estruturas de dados na memória e diferentes formatos: CSV e arquivos de texto, Microsoft Excel, bancos de dados SQL e o rápido formato HDF5;

- Alinhamento inteligente de dados e tratamento integrado de dados ausentes: obtenha alinhamento automático baseado em rótulos em cálculos e manipule facilmente dados confusos em uma forma ordenada;

- Reformulação flexível e dinamização de conjuntos de dados;

- Corte inteligente baseado em rótulos, indexação sofisticada e subconjunto de grandes conjuntos de dados;

- As colunas podem ser inseridas e excluídas das estruturas de dados para mutabilidade de tamanho;

- Agregar ou transformar dados com um poderoso grupo por mecanismo, permitindo operações de divisão-aplicação-combinação em conjuntos de dados;

- Fusão e união de conjuntos de dados de alto desempenho;

- A indexação de eixo hierárquico fornece uma maneira intuitiva de trabalhar com dados de alta dimensão em uma estrutura de dados de dimensão inferior;

- Funcionalidade de série temporal: geração de intervalo de datas e conversão de frequência, estatísticas de janela móvel, mudança de data e atraso. Crie até mesmo deslocamentos de tempo específicos do domínio e junte-se a séries temporais sem perder dados;

- Altamente otimizado para desempenho, com caminhos de código críticos escritos em Cython ou C.

- Python com pandas está em uso em uma ampla variedade de domínios acadêmicos e comerciais, incluindo Finanças, Neurociência, Economia, Estatística, Publicidade, Web Analytics e muito mais.

##DataFrame

In [ ]:
# importando a biblioteca pandas
import pandas as pd

In [ ]:
# carregando um arquivo csv para dataframe pandas | pd.read_csv
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/DS - Felipe Amaral/Material do curso/7.Prática em Python/dados/Credit.csv')

In [ ]:
# quantidade de linhas e colunas com | .shape
df.shape

(1000, 21)

In [ ]:
# informações do dataframe | .info()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 21 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   checking_status         1000 non-null   object
 1   duration                1000 non-null   int64
 2   credit_history          1000 non-null   object
 3   purpose                 1000 non-null   object
 4   credit_amount           1000 non-null   int64
 5   savings_status          1000 non-null   object
 6   employment              1000 non-null   object
 7   installment_commitment  1000 non-null   int64
 8   personal_status         1000 non-null   object
 9   other_parties           1000 non-null   object
 10  residence_since         1000 non-null   int64
 11  property_magnitude      1000 non-null   object
 12  age                     1000 non-null   int64
 13  other_payment_plans     1000 non-null   object
 14  housing                 1000 non-null   object
 15  existing_credits        1000 non-null   int64
 16  job                     1000 non-null   object
 17  num_dependents          1000 non-null   int64
 18  own_telephone           1000 non-null   object
 19  foreign_worker          1000 non-null   object
 20  class                   1000 non-null   object
dtypes: int64(7), object(14)
memory usage: 164.2+ KB

In [ ]:
# resumo estatístico das colunas numéricas | .describe()
df.describe()

,duration,credit_amount,installment_commitment,residence_since,age,existing_credits,num_dependents
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,20.903000,3271.258000,2.973000,2.845000,35.546000,1.407000,1.155000
std,12.058814,2822.736876,1.118715,1.103718,11.375469,0.577654,0.362086
min,4.000000,250.000000,1.000000,1.000000,19.000000,1.000000,1.000000
25%,12.000000,1365.500000,2.000000,2.000000,27.000000,1.000000,1.000000
50%,18.000000,2319.500000,3.000000,3.000000,33.000000,1.000000,1.000000
75%,24.000000,3972.250000,4.000000,4.000000,42.000000,2.000000,1.000000
max,72.000000,18424.000000,4.000000,4.000000,75.000000,4.000000,2.000000

In [ ]:
# 5 primeiros registros | .head()
df.head()

,checking_status,duration,credit_history,purpose,credit_amount,savings_status,employment,installment_commitment,personal_status,other_parties,...,property_magnitude,age,other_payment_plans,housing,existing_credits,job,num_dependents,own_telephone,foreign_worker,class
0,<0,6,'critical/other existing credit',radio/tv,1169,'no known savings',>=7,4,'male single',none,...,'real estate',67,none,own,2,skilled,1,yes,yes,good
1,0<=X<200,48,'existing paid',radio/tv,5951,<100,1<=X<4,2,'female div/dep/mar',none,...,'real estate',22,none,own,1,skilled,1,none,yes,bad
2,'no checking',12,'critical/other existing credit',education,2096,<100,4<=X<7,2,'male single',none,...,'real estate',49,none,own,1,'unskilled resident',2,none,yes,good
3,<0,42,'existing paid',furniture/equipment,7882,<100,4<=X<7,2,'male single',guarantor,...,'life insurance',45,none,'for free',1,skilled,2,none,yes,good
4,<0,24,'delayed previously','new car',4870,<100,1<=X<4,3,'male single',none,...,'no known property',53,none,'for free',2,skilled,2,none,yes,bad

In [ ]:
# 2 últimos registros | .tail()
df.tail(2)

,checking_status,duration,credit_history,purpose,credit_amount,savings_status,employment,installment_commitment,personal_status,other_parties,...,property_magnitude,age,other_payment_plans,housing,existing_credits,job,num_dependents,own_telephone,foreign_worker,class
998,<0,45,'existing paid',radio/tv,1845,<100,1<=X<4,4,'male single',none,...,'no known property',23,none,'for free',1,skilled,1,yes,yes,bad
999,0<=X<200,45,'critical/other existing credit','used car',4576,100<=X<500,unemployed,3,'male single',none,...,car,27,none,own,1,skilled,1,none,yes,good

In [ ]:
# filtro por nome de coluna
df['duration']

0       6
1      48
2      12
3      42
4      24
       ..
995    12
996    30
997    12
998    45
999    45
Name: duration, Length: 1000, dtype: int64

**loc[]** -  Acesse um grupo de linhas e colunas pelo índice. É baseado principalmente em rótulos.

As entradas permitidas são:

- Linhas com apenas um índice, por ex. 5 ou 'a', (observe que 5 é interpretado como um rótulo do índice, e nunca como uma posição inteira ao longo do índice);

- Índices separados ou matriz de rótulos, por exemplo ['a', 'b', 'c'];

- Uma faixa de índices, por exemplo 'a':'f'

In [ ]:
# filtrar linhas por índice | .loc[]
df.loc[1:3] #  linhas com índice de 1 a 3 (inclusive)

,checking_status,duration,credit_history,purpose,credit_amount,savings_status,employment,installment_commitment,personal_status,other_parties,...,property_magnitude,age,other_payment_plans,housing,existing_credits,job,num_dependents,own_telephone,foreign_worker,class
1,0<=X<200,48,'existing paid',radio/tv,5951,<100,1<=X<4,2,'female div/dep/mar',none,...,'real estate',22,none,own,1,skilled,1,none,yes,bad
2,'no checking',12,'critical/other existing credit',education,2096,<100,4<=X<7,2,'male single',none,...,'real estate',49,none,own,1,'unskilled resident',2,none,yes,good
3,<0,42,'existing paid',furniture/equipment,7882,<100,4<=X<7,2,'male single',guarantor,...,'life insurance',45,none,'for free',1,skilled,2,none,yes,good

In [ ]:
# linhas 1 e 3 | .loc[]
df.loc[[1, 3]] # índice 1 e 3

,checking_status,duration,credit_history,purpose,credit_amount,savings_status,employment,installment_commitment,personal_status,other_parties,...,property_magnitude,age,other_payment_plans,housing,existing_credits,job,num_dependents,own_telephone,foreign_worker,class
1,0<=X<200,48,'existing paid',radio/tv,5951,<100,1<=X<4,2,'female div/dep/mar',none,...,'real estate',22,none,own,1,skilled,1,none,yes,bad
3,<0,42,'existing paid',furniture/equipment,7882,<100,4<=X<7,2,'male single',guarantor,...,'life insurance',45,none,'for free',1,skilled,2,none,yes,good

In [ ]:
# filtro de coluna com um determinado valor | condicional de igualdade
df.loc[df['purpose'] == 'radio/tv']

,checking_status,duration,credit_history,purpose,credit_amount,savings_status,employment,installment_commitment,personal_status,other_parties,...,property_magnitude,age,other_payment_plans,housing,existing_credits,job,num_dependents,own_telephone,foreign_worker,class
0,<0,6,'critical/other existing credit',radio/tv,1169,'no known savings',>=7,4,'male single',none,...,'real estate',67,none,own,2,skilled,1,yes,yes,good
1,0<=X<200,48,'existing paid',radio/tv,5951,<100,1<=X<4,2,'female div/dep/mar',none,...,'real estate',22,none,own,1,skilled,1,none,yes,bad
8,'no checking',12,'existing paid',radio/tv,3059,>=1000,4<=X<7,2,'male div/sep',none,...,'real estate',61,none,own,1,'unskilled resident',1,none,yes,good
12,0<=X<200,12,'existing paid',radio/tv,1567,<100,1<=X<4,1,'female div/dep/mar',none,...,car,22,none,own,1,skilled,1,yes,yes,good
15,<0,24,'existing paid',radio/tv,1282,100<=X<500,1<=X<4,4,'female div/dep/mar',none,...,car,32,none,own,1,'unskilled resident',1,none,yes,bad
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
989,0<=X<200,24,'critical/other existing credit',radio/tv,1743,<100,>=7,4,'male single',none,...,'life insurance',48,none,own,2,'unskilled resident',1,none,yes,good
991,'no checking',15,'all paid',radio/tv,1569,100<=X<500,>=7,4,'male single',none,...,car,34,bank,own,1,'unskilled resident',2,none,yes,good
992,<0,18,'existing paid',radio/tv,1936,'no known savings',4<=X<7,2,'male mar/wid',none,...,car,23,none,rent,2,'unskilled resident',1,none,yes,good
997,'no checking',12,'existing paid',radio/tv,804,<100,>=7,4,'male single',none,...,car,38,none,own,1,skilled,1,none,yes,good
998,<0,45,'existing paid',radio/tv,1845,<100,1<=X<4,4,'male single',none,...,'no known property',23,none,'for free',1,skilled,1,yes,yes,bad

In [ ]:
# filtro de coluna com um determinado valor | condicional de maior que
df.loc[df['credit_amount'] > 18000]

,checking_status,duration,credit_history,purpose,credit_amount,savings_status,employment,installment_commitment,personal_status,other_parties,...,property_magnitude,age,other_payment_plans,housing,existing_credits,job,num_dependents,own_telephone,foreign_worker,class
915,0<=X<200,48,'no credits/all paid',other,18424,<100,1<=X<4,1,'female div/dep/mar',none,...,'life insurance',32,bank,own,1,'high qualif/self emp/mgmt',1,yes,no,bad

In [ ]:
# atribuindo o resultado acima a uma variável, criando outro df
df2 = df.loc[df['credit_amount'] > 18000]
df2

,checking_status,duration,credit_history,purpose,credit_amount,savings_status,employment,installment_commitment,personal_status,other_parties,...,property_magnitude,age,other_payment_plans,housing,existing_credits,job,num_dependents,own_telephone,foreign_worker,class
915,0<=X<200,48,'no credits/all paid',other,18424,<100,1<=X<4,1,'female div/dep/mar',none,...,'life insurance',32,bank,own,1,'high qualif/self emp/mgmt',1,yes,no,bad

In [ ]:
type(df2)

pandas.core.frame.DataFrame

In [ ]:
# extraindo apenas duas colunas com  filtro condicional em outra coluna
df[['checking_status','duration']].loc[df['credit_amount'] > 18000]

    checking_status  duration
915        0<=X<200        48

## Series

Series: apenas uma única coluna

Pode ser criada a partir de listas, array do numpy ou coluna de data frame

In [ ]:
import pandas as pd

In [ ]:
# pandas series através de listas
s1 = pd.Series([2,5,3,34,54,23,1,16])
s1

0     2
1     5
2     3
3    34
4    54
5    23
6     1
7    16
dtype: int64

In [ ]:
type(s1)

pandas.core.series.Series

In [ ]:
# pandas series através de um array do Numpy
import numpy as np

In [ ]:
array1 = np.array([2,5,3,34,54,23,1,16])
array1

array([ 2,  5,  3, 34, 54, 23,  1, 16])

In [ ]:
type(array1)

numpy.ndarray

In [ ]:
# pandas series a partir de um array do numpy
s2 = pd.Series(array1)
print(s2)
print(type(s2))

0     2
1     5
2     3
3    34
4    54
5    23
6     1
7    16
dtype: int64
<class 'pandas.core.series.Series'>

In [ ]:
# series a partir de um dataframe
s3 = df['purpose']

s3.head()

0               radio/tv
1               radio/tv
2              education
3    furniture/equipment
4              'new car'
Name: purpose, dtype: object

In [ ]:
type(s3)

pandas.core.series.Series

In [ ]:
# quando colocamos dois colchetes para selecionar a coluna
# o output é um dataframe
d4 = df[['purpose']]
d4.head()

               purpose
0             radio/tv
1             radio/tv
2            education
3  furniture/equipment
4            'new car'

In [ ]:
type(d4)

pandas.core.frame.DataFrame

## Renomeando coluna

In [ ]:
# renomeando coluna | .rename()
df.rename(columns={'duration':'duração', 'purpose':'propósito'}).head()

,checking_status,duração,credit_history,propósito,credit_amount,savings_status,employment,installment_commitment,personal_status,other_parties,...,property_magnitude,age,other_payment_plans,housing,existing_credits,job,num_dependents,own_telephone,foreign_worker,class
0,<0,6,'critical/other existing credit',radio/tv,1169,'no known savings',>=7,4,'male single',none,...,'real estate',67,none,own,2,skilled,1,yes,yes,good
1,0<=X<200,48,'existing paid',radio/tv,5951,<100,1<=X<4,2,'female div/dep/mar',none,...,'real estate',22,none,own,1,skilled,1,none,yes,bad
2,'no checking',12,'critical/other existing credit',education,2096,<100,4<=X<7,2,'male single',none,...,'real estate',49,none,own,1,'unskilled resident',2,none,yes,good
3,<0,42,'existing paid',furniture/equipment,7882,<100,4<=X<7,2,'male single',guarantor,...,'life insurance',45,none,'for free',1,skilled,2,none,yes,good
4,<0,24,'delayed previously','new car',4870,<100,1<=X<4,3,'male single',none,...,'no known property',53,none,'for free',2,skilled,2,none,yes,bad

In [ ]:
# definindo o parâmetro inplace = True para fazer a mudança de forma definitiva
df.rename(columns={'duration':'duração', 'purpose':'propósito'},
          inplace = True)

In [ ]:
df[['duração', 'propósito']]

     duração            propósito
0          6             radio/tv
1         48             radio/tv
2         12            education
3         42  furniture/equipment
4         24            'new car'
..       ...                  ...
995       12  furniture/equipment
996       30           'used car'
997       12             radio/tv
998       45             radio/tv
999       45           'used car'

[1000 rows x 2 columns]

## Excluindo colunas

In [ ]:
# excluindo colunas | .drop()
# parâmetro axis = 1 para remover coluna e axis = 0 para remover linha(índice)
df.drop('checking_status', axis = 1)

# outra opção, passando como parâmetro "columns"
# df.drop(columns= ['checking_status'])

,duração,credit_history,propósito,credit_amount,savings_status,employment,installment_commitment,personal_status,other_parties,residence_since,property_magnitude,age,other_payment_plans,housing,existing_credits,job,num_dependents,own_telephone,foreign_worker,class
0,6,'critical/other existing credit',radio/tv,1169,'no known savings',>=7,4,'male single',none,4,'real estate',67,none,own,2,skilled,1,yes,yes,good
1,48,'existing paid',radio/tv,5951,<100,1<=X<4,2,'female div/dep/mar',none,2,'real estate',22,none,own,1,skilled,1,none,yes,bad
2,12,'critical/other existing credit',education,2096,<100,4<=X<7,2,'male single',none,3,'real estate',49,none,own,1,'unskilled resident',2,none,yes,good
3,42,'existing paid',furniture/equipment,7882,<100,4<=X<7,2,'male single',guarantor,4,'life insurance',45,none,'for free',1,skilled,2,none,yes,good
4,24,'delayed previously','new car',4870,<100,1<=X<4,3,'male single',none,4,'no known property',53,none,'for free',2,skilled,2,none,yes,bad
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,12,'existing paid',furniture/equipment,1736,<100,4<=X<7,3,'female div/dep/mar',none,4,'real estate',31,none,own,1,'unskilled resident',1,none,yes,good
996,30,'existing paid','used car',3857,<100,1<=X<4,4,'male div/sep',none,4,'life insurance',40,none,own,1,'high qualif/self emp/mgmt',1,yes,yes,good
997,12,'existing paid',radio/tv,804,<100,>=7,4,'male single',none,4,car,38,none,own,1,skilled,1,none,yes,good
998,45,'existing paid',radio/tv,1845,<100,1<=X<4,4,'male single',none,4,'no known property',23,none,'for free',1,skilled,1,yes,yes,bad
999,45,'critical/other existing credit','used car',4576,100<=X<500,unemployed,3,'male single',none,4,car,27,none,own,1,skilled,1,none,yes,good

In [ ]:
# inplace = True para fazer a exclusão definitiva da coluna
df.drop(columns= ['checking_status'], inplace = True)

In [ ]:
df.head(2)

,duração,credit_history,propósito,credit_amount,savings_status,employment,installment_commitment,personal_status,other_parties,residence_since,property_magnitude,age,other_payment_plans,housing,existing_credits,job,num_dependents,own_telephone,foreign_worker,class
0,6,'critical/other existing credit',radio/tv,1169,'no known savings',>=7,4,'male single',none,4,'real estate',67,none,own,2,skilled,1,yes,yes,good
1,48,'existing paid',radio/tv,5951,<100,1<=X<4,2,'female div/dep/mar',none,2,'real estate',22,none,own,1,skilled,1,none,yes,bad

## Dados nulos

Observação:

isna() - detecta valores ausentes e retorna um valor booleano indicando se os valores são NA. Valores NA, como None ou numpy.NaN, são mapeados para valores True. Todo o resto é mapeado para valores False. Caracteres como strings vazias '' ou numpy.inf não são considerados valores NA (a menos que você defina pandas.options.mode.use_inf_as_na = True).

isnull() - DataFrame.isnull é um pseudômino para DataFrame.isna.

In [ ]:
# verificando dados nulos | pandas.DataFrame.isnull()

df.isnull()

,duração,credit_history,propósito,credit_amount,savings_status,employment,installment_commitment,personal_status,other_parties,residence_since,property_magnitude,age,other_payment_plans,housing,existing_credits,job,num_dependents,own_telephone,foreign_worker,class
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
# somando os dados nulos por coluna
df.isnull().sum()

duração                   0
credit_history            0
propósito                 0
credit_amount             0
savings_status            0
employment                0
installment_commitment    0
personal_status           0
other_parties             0
residence_since           0
property_magnitude        0
age                       0
other_payment_plans       0
housing                   0
existing_credits          0
job                       0
num_dependents            0
own_telephone             0
foreign_worker            0
class                     0
dtype: int64

In [ ]:
# removendo linhas onde pelo menos um campo do registro é nulo | pandas.DataFrame.dropna()
df.dropna()

,duração,credit_history,propósito,credit_amount,savings_status,employment,installment_commitment,personal_status,other_parties,residence_since,property_magnitude,age,other_payment_plans,housing,existing_credits,job,num_dependents,own_telephone,foreign_worker,class
0,6,'critical/other existing credit',radio/tv,1169,'no known savings',>=7,4,'male single',none,4,'real estate',67,none,own,2,skilled,1,yes,yes,good
1,48,'existing paid',radio/tv,5951,<100,1<=X<4,2,'female div/dep/mar',none,2,'real estate',22,none,own,1,skilled,1,none,yes,bad
2,12,'critical/other existing credit',education,2096,<100,4<=X<7,2,'male single',none,3,'real estate',49,none,own,1,'unskilled resident',2,none,yes,good
3,42,'existing paid',furniture/equipment,7882,<100,4<=X<7,2,'male single',guarantor,4,'life insurance',45,none,'for free',1,skilled,2,none,yes,good
4,24,'delayed previously','new car',4870,<100,1<=X<4,3,'male single',none,4,'no known property',53,none,'for free',2,skilled,2,none,yes,bad
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,12,'existing paid',furniture/equipment,1736,<100,4<=X<7,3,'female div/dep/mar',none,4,'real estate',31,none,own,1,'unskilled resident',1,none,yes,good
996,30,'existing paid','used car',3857,<100,1<=X<4,4,'male div/sep',none,4,'life insurance',40,none,own,1,'high qualif/self emp/mgmt',1,yes,yes,good
997,12,'existing paid',radio/tv,804,<100,>=7,4,'male single',none,4,car,38,none,own,1,skilled,1,none,yes,good
998,45,'existing paid',radio/tv,1845,<100,1<=X<4,4,'male single',none,4,'no known property',23,none,'for free',1,skilled,1,yes,yes,bad
999,45,'critical/other existing credit','used car',4576,100<=X<500,unemployed,3,'male single',none,4,car,27,none,own,1,skilled,1,none,yes,good

In [ ]:
# substituindo valores nulos por parâmetro passado | pandas.DataFrame.fillna()
df.fillna(0, inplace = True) # se houver valor nulo, será substituído por 0

## Consulta por índice (iloc)

In [ ]:
df.head()

,duração,credit_history,propósito,credit_amount,savings_status,employment,installment_commitment,personal_status,other_parties,residence_since,property_magnitude,age,other_payment_plans,housing,existing_credits,job,num_dependents,own_telephone,foreign_worker,class
0,6,'critical/other existing credit',radio/tv,1169,'no known savings',>=7,4,'male single',none,4,'real estate',67,none,own,2,skilled,1,yes,yes,good
1,48,'existing paid',radio/tv,5951,<100,1<=X<4,2,'female div/dep/mar',none,2,'real estate',22,none,own,1,skilled,1,none,yes,bad
2,12,'critical/other existing credit',education,2096,<100,4<=X<7,2,'male single',none,3,'real estate',49,none,own,1,'unskilled resident',2,none,yes,good
3,42,'existing paid',furniture/equipment,7882,<100,4<=X<7,2,'male single',guarantor,4,'life insurance',45,none,'for free',1,skilled,2,none,yes,good
4,24,'delayed previously','new car',4870,<100,1<=X<4,3,'male single',none,4,'no known property',53,none,'for free',2,skilled,2,none,yes,bad

In [ ]:
# extraindo dados apenas das linhas com índice de 0 até 3 (o 4 é exclusivo) e
# colunas de 0 a 2
df.iloc[0:4, 0:3]

   duração                    credit_history            propósito
0        6  'critical/other existing credit'             radio/tv
1       48                   'existing paid'             radio/tv
2       12  'critical/other existing credit'            education
3       42                   'existing paid'  furniture/equipment

In [ ]:
# extraindo dados apenas das linhas com índice 0, 1, 2, 3 e 7
# colunas de 0 a 5
df.iloc[[0,1,2,3,7],0:5]

,duração,credit_history,propósito,credit_amount,savings_status
0,6,'critical/other existing credit',radio/tv,1169,'no known savings'
1,48,'existing paid',radio/tv,5951,<100
2,12,'critical/other existing credit',education,2096,<100
3,42,'existing paid',furniture/equipment,7882,<100
7,36,'existing paid','used car',6948,<100